variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - e2e_test

.e2e_on_cluster_template:
  stage: e2e_test
  script:
    - ./e2e/cluster.sh clusterUp
    - ./install/installer.sh install
    - kubectl patch storageclass csi-cephfs-sc -p '{"metadata"':' {"annotations":{"storageclass.kubernetes.io/is-default-class"':'"true"}}}' #TODO 추후 변경
    - kubectl get po -n rook-ceph # TODO 추후 삭제
    - ./install/installer.sh test
    - ./install/installer.sh uninstall
  after_script:
    - ./e2e/cluster.sh clusterClean

.e2e_on_minikube_template:
  stage: e2e_test
  script:
    - ./e2e/cluster.sh minikubeUp
    - ./install/installer.sh install --minikube
    - kubectl patch storageclass standard -p '{"metadata"':' {"annotations":{"storageclass.kubernetes.io/is-default-class"':'"false"}}}' && kubectl patch storageclass csi-cephfs-sc -p '{"metadata"':' {"annotations":{"storageclass.kubernetes.io/is-default-class"':'"true"}}}' #TODO 추후 변경
    - kubectl get po -n rook-ceph # TODO 추후 삭제
    - ./install/installer.sh test
    - ./install/installer.sh uninstall --minikube
  after_script:
    - ./e2e/cluster.sh minikubeClean

e2e_test_centos_2node_1_15_3:
  extends: .e2e_on_cluster_template
  before_script:
    - export BOX_OS=centos NODE_COUNT=2 KUBERNETES_VERSION=1.15.3

e2e_test_centos_3node_1_15_3:
  extends: .e2e_on_cluster_template
  before_script:
    - export BOX_OS=centos NODE_COUNT=3 KUBERNETES_VERSION=1.15.3

#e2e_test_minikube_1_17_3:
#  extends: .e2e_on_minikube_template
#  before_script:
#    - export KUBERNETES_VERSION=1.17.3
