variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - e2e_test

.e2e_on_cluster_template:
  stage: e2e_test
  script:
    - ./e2e/cluster.sh clusterUp
    - echo "helm install"
    - echo "wait until helm install"
    - echo "go setting"
    - echo "go test"
  after_script:
    - echo "helm uninstall"
    - echo "wait until helm uninstall"
    - ./e2e/cluster.sh clusterClean

.e2e_on_minikube_template:
  stage: e2e_test
  script:
    - ./e2e/cluster.sh minikubeUp
    - minikube ssh "sudo mkdir -p /var/lib/rook; sudo mkdir -p /mnt/sda1/var/lib/rook"
    - helm install hypercloud-storage ./charts
    - ./charts/hack.sh wait_hypercloud_storage_available #TODO 추후 변경
    - kubectl patch storageclass standard -p '{"metadata"':' {"annotations":{"storageclass.kubernetes.io/is-default-class"':'"false"}}}' && kubectl patch storageclass csi-cephfs -p '{"metadata"':' {"annotations":{"storageclass.kubernetes.io/is-default-class"':'"true"}}}' #TODO 추후 변경
    - export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin && export GO111MODULE=auto # go setting
    - cd ./e2e && go get ./... && ginkgo # go test
    - echo bye
  after_script:
    - helm delete hypercloud-storage
    - ./charts/hack.sh wait_hypercloud_storage_deleted #TODO 추후 변경
    - minikube ssh "sudo rm -rf /mnt/sda1/var/lib/rook; sudo rm -rf /var/lib/rook"
    - ./e2e/cluster.sh minikubeClean

#e2e_test_centos_1node_1_17_3:
#  extends: .e2e_on_cluster_template
#  before_script:
#    - export BOX_OS=centos NODE_COUNT=1 KUBERNETES_VERSION=1.17.3
#
#e2e_test_centos_3node_1_15_3:
#  extends: .e2e_on_cluster_template
#  before_script:
#    - export BOX_OS=centos NODE_COUNT=3 KUBERNETES_VERSION=1.15.3

e2e_test_minikube_1_17_3:
  extends: .e2e_on_minikube_template
  before_script:
    - export KUBERNETES_VERSION=1.17.3
