variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - e2e_test

.e2e_on_cluster_template:
  stage: e2e_test
  script:
    - ./hack/cluster.sh clusterUp
    - make -C hcsctl && export PATH=$PATH:$(pwd)/hcsctl/build
    - hcsctl install hack/inventory/sample
    - hcsctl.test
    - hcsctl uninstall hack/inventory/sample
  after_script:
    - ./hack/cluster.sh clusterClean

e2e_test_centos_3node_1_15_3:
  extends: .e2e_on_cluster_template
  before_script:
    - export BOX_OS=centos NODE_COUNT=2 KUBERNETES_VERSION=1.15.3
e2e_test_centos_3node_1_16_8:
  extends: .e2e_on_cluster_template
  before_script:
    - export BOX_OS=centos NODE_COUNT=2 KUBERNETES_VERSION=1.16.8
e2e_test_centos_3node_1_15_3_flannel:
  extends: .e2e_on_cluster_template
  before_script:
    - export BOX_OS=centos NODE_COUNT=2 KUBE_NETWORK=flannel KUBERNETES_VERSION=1.15.3
e2e_test_ubuntu_3node_1_17_4:
  extends: .e2e_on_cluster_template
  before_script:
    - export BOX_OS=ubuntu NODE_COUNT=2 KUBERNETES_VERSION=1.17.4
