stages:
  - build
  - unit_test
  - e2e_test
  - deploy

build:
  stage: build
  script:
    - make build

unit_test:
  stage: unit_test
  script:
    - make unit

e2e_test:
  stage: e2e_test
  script:
    - make clusterClean
    - make clusterUp
    - make install
    - make e2e
  after_script:
    - make uninstall
    - make clusterClean

deploy:
  stage: deploy
  script:
    - echo "deploy ok"
