apiVersion: v1
entries:
  rook-ceph-init:
  - apiVersion: v2
    appVersion: 1.2.4
    created: "2020-02-21T14:33:10.245550199+09:00"
    description: A Helm chart for rook-ceph init
    digest: 77478ab85da86fb34cb6a2b8029f524f164aba4f604c5e6d208efa596eba2750
    name: rook-ceph-init
    type: application
    urls:
    - package/rook-ceph-init-1.0.0.tgz
    version: 1.0.0
generated: "2020-02-21T14:33:10.244968868+09:00"
