name: hypercloud-stroage
on:
  push:
    branches:
      - master
    tages:
      - v*
  pull_request:
jobs:
  lint:
    runs-on: prolinux
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
          make check -C hcsctl
  build:
    runs-on: prolinux
    timeout-minutes: 3
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          go get github.com/markbates/pkger/cmd/pkger
          make -C hcsctl
  e2e_v1_15_3_calico:
    runs-on: prolinux
    needs: [lint, build]
    timeout-minutes: 20
    steps:
      - run: |
          export BOX_OS=prolinux KUBE_VERSION=v1.15.3 KUBE_NETWORK=calico
          ./hack/prolinux_cluster.sh up
          ./hcsctl/build/hcsctl install ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl ceph status
          ./hcsctl/build/hcsctl ceph exec ceph osd status
          ./hcsctl/build/hcsctl.test
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample # idempotent
  e2e_v1_15_3_flannel:
    runs-on: prolinux
    needs: [lint, build]
    timeout-minutes: 20
    steps:
      - run: |
          export BOX_OS=prolinux KUBE_VERSION=v1.15.3 KUBE_NETWORK=flannel
          ./hack/prolinux_cluster.sh up
          ./hcsctl/build/hcsctl install ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl ceph status
          ./hcsctl/build/hcsctl ceph exec ceph osd status
          ./hcsctl/build/hcsctl.test
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample # idempotent
  e2e_v1_15_3_calico_with_another_kubeconfigpath:
    runs-on: prolinux
    needs: [lint, build]
    timeout-minutes: 20
    steps:
      - run: |
          export BOX_OS=prolinux KUBE_VERSION=v1.15.3 KUBE_NETWORK=calico
          ./hack/prolinux_cluster.sh up
          mv $HOME/.kube/config $HOME/config
          ./hcsctl/build/hcsctl install ./hack/inventory/test-sample --kubeconfig $HOME/config
          ./hcsctl/build/hcsctl ceph status --kubeconfig=$HOME/config
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample --kubeconfig $HOME/config
          mv $HOME/config $HOME/.kube/config
  e2e_cleanup:
    runs-on: prolinux
    needs: [lint, build, e2e_v1_15_3_calico, e2e_v1_15_3_flannel, e2e_v1_15_3_calico_with_another_kubeconfigpath]
    timeout-minutes: 10
    steps:
      - run: ./hack/prolinux_cluster.sh down
