name: hypercloud-stroage
on:
  push:
    branches:
      - master
    tages:
      - v*
  pull_request:
jobs:
  lint:
    runs-on: prolinux
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
          make check -C hcsctl
  build:
    runs-on: prolinux
    timeout-minutes: 3
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
          go get github.com/markbates/pkger/cmd/pkger
          make -C hcsctl
  e2e:
    runs-on: prolinux
    timeout-minutes: 20
    steps:
      - run: |
          ./hcsctl/build/hcsctl install ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl ceph status
          ./hcsctl/build/hcsctl ceph exec ceph osd status
          ./hcsctl/build/hcsctl.test
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample # idempotent
