# This is a basic workflow to help you get started with Actions

name: hypercloud-stroage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
  # This workflow contains a single job called "build":
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: make -C hcsctl
      working-directory: hcsctl/build/
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: |
          ./hcsctl/build/hcsctl install ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl ceph status
          ./hcsctl/build/hcsctl ceph exec ceph osd status
          ./hcsctl/build/hcsctl.test
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample
          ./hcsctl/build/hcsctl uninstall ./hack/inventory/test-sample # idempotent
